[build]
  publish = "build/"
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  REACT_APP_MY_APP_ID="feedbackist"
  REACT_APP_MY_APP_ENDPOINT="https://feedbackist-mgif7knuia-uc.a.run.app/graphql"
